# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu accounts.tf — aws_organizations_account resources
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T06:59:02.823245Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Mandatory accounts
resource "aws_organizations_account" "logarchive" {
  name      = "LogArchive"
  email     = "aws-logarchive@example.com"
  parent_id = aws_organizations_organizational_unit.security.id
  role_name = "OrganizationAccountAccessRole"
  iam_user_access_to_billing = "DENY"
  close_on_deletion = false

  lifecycle {
    ignore_changes = [role_name]
  }
}
resource "aws_organizations_account" "audit" {
  name      = "Audit"
  email     = "aws-audit@example.com"
  parent_id = aws_organizations_organizational_unit.security.id
  role_name = "OrganizationAccountAccessRole"
  iam_user_access_to_billing = "DENY"
  close_on_deletion = false

  lifecycle {
    ignore_changes = [role_name]
  }
}
resource "aws_organizations_account" "sharedservices" {
  name      = "SharedServices"
  email     = "aws-shared@example.com"
  parent_id = aws_organizations_organizational_unit.infrastructure.id
  role_name = "OrganizationAccountAccessRole"
  iam_user_access_to_billing = "DENY"
  close_on_deletion = false

  lifecycle {
    ignore_changes = [role_name]
  }
}
resource "aws_organizations_account" "network" {
  name      = "Network"
  email     = "aws-network@example.com"
  parent_id = aws_organizations_organizational_unit.infrastructure.id
  role_name = "OrganizationAccountAccessRole"
  iam_user_access_to_billing = "DENY"
  close_on_deletion = false

  lifecycle {
    ignore_changes = [role_name]
  }
}

# Workload accounts
resource "aws_organizations_account" "pciworkload" {
  name      = "PciWorkload"
  email     = "aws-pci-workload@example.com"
  parent_id = aws_organizations_organizational_unit.workloads_prod_pci.id
  role_name = "OrganizationAccountAccessRole"
  iam_user_access_to_billing = "DENY"
  close_on_deletion = false

  lifecycle {
    ignore_changes = [role_name]
  }
}
resource "aws_organizations_account" "appdev" {
  name      = "AppDev"
  email     = "aws-appdev@example.com"
  parent_id = aws_organizations_organizational_unit.workloads_dev.id
  role_name = "OrganizationAccountAccessRole"
  iam_user_access_to_billing = "DENY"
  close_on_deletion = false

  lifecycle {
    ignore_changes = [role_name]
  }
}
resource "aws_organizations_account" "appprod" {
  name      = "AppProd"
  email     = "aws-appprod@example.com"
  parent_id = aws_organizations_organizational_unit.workloads_prod.id
  role_name = "OrganizationAccountAccessRole"
  iam_user_access_to_billing = "DENY"
  close_on_deletion = false

  lifecycle {
    ignore_changes = [role_name]
  }
}

# Export a convenient map of created account IDs
locals {
  created_account_ids = merge(
    { for k, v in {
        "LogArchive" = aws_organizations_account.logarchive.id,
        "Audit" = aws_organizations_account.audit.id,
        "SharedServices" = aws_organizations_account.sharedservices.id,
        "Network" = aws_organizations_account.network.id,
        "PciWorkload" = aws_organizations_account.pciworkload.id,
        "AppDev" = aws_organizations_account.appdev.id,
        "AppProd" = aws_organizations_account.appprod.id,
    } : k => v },
    {}
  )
}