# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu backend.tf — remote state in S3 + DynamoDB locking
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T06:59:02.823245Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Remote state bucket lives in the management account; lock table in DynamoDB.
# Bootstrap this bucket + table OUT-OF-BAND before first `tofu init`.

terraform {
  backend "s3" {
    bucket         = "acme-bank-tofu-state"
    key            = "aws-landing-zone/terraform.tfstate"
    region         = "us-east-2"
    encrypt        = true
    kms_key_id     = "alias/accelerator/kms/key"
    dynamodb_table = "acme-bank-tofu-state-lock"
  }
}