# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu providers.tf
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T06:59:02.823245Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Default provider: home region
provider "aws" {
  region = "us-east-2"

  default_tags {
    tags = local.default_tags
  }
}

locals {
  default_tags = {
    ManagedBy    = "Merlin-Studio-v2"
    Organization = "Acme Bank"
    Profile      = "standard"
    Environment  = "multi_env"
    CostCenter   = "PLATFORM"
    Compliance   = "cis,pci_dss,sox"
  }
}

provider "aws" {
  alias  = "backup_dr"
  region = "us-west-2"
  default_tags {
    tags = local.default_tags
  }
}

provider "aws" {
  alias  = "appprod"
  region = "us-east-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppProd:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appprod-us-east-2"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "appprod_us_west_2"
  region = "us-west-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppProd:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appprod-us-west-2"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "network"
  region = "us-east-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Network:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-network-us-east-2"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "network_us_west_2"
  region = "us-west-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Network:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-network-us-west-2"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "pciworkload"
  region = "us-east-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_PciWorkload:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-pciworkload-us-east-2"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Provider for log archive account (cross-account writes)
provider "aws" {
  alias  = "log_archive"
  region = "us-east-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-log-archive"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Log archive account, us-west-2 — hosts the central-logs
# CMK replica so the replicated log bucket's objects are decryptable in DR.
provider "aws" {
  alias  = "log_archive_us_west_2"
  region = "us-west-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-log-archive-us-west-2"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Provider for audit / security tooling account
provider "aws" {
  alias  = "audit"
  region = "us-east-2"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Audit:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-audit"
  }
  default_tags {
    tags = local.default_tags
  }
}