# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — AWS account inventory tfvars
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T07:01:13.110408Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Consumed by a Terraform module that wraps aws_organizations_account.
# IMPORTANT: each email must be globally unique across all AWS accounts.

mandatory_accounts = {
  Management = {
    email               = "my1mail@acme.com"
    organizational_unit = "Root"
    description         = "AWS Organizations management / payer account"
  }
  LogArchive = {
    email               = "aws-logarchive@example.com"
    organizational_unit = "Security"
    description         = "Central log archive (CloudTrail, Config)"
  }
  Audit = {
    email               = "aws-audit@example.com"
    organizational_unit = "Security"
    description         = "Security tooling delegated administrator"
  }
  SharedServices = {
    email               = "aws-shared@example.com"
    organizational_unit = "Infrastructure"
    description         = "Shared services (DNS, golden AMIs, etc.)"
  }
  Network = {
    email               = "aws-network@example.com"
    organizational_unit = "Infrastructure"
    description         = "Central network hub (TGW, DX, perimeter VPCs)"
  }
}

workload_accounts = {
  PciWorkload = {
    email               = "aws-pci-workload@example.com"
    organizational_unit = "Workloads/Prod/PCI"
    description         = "Dedicated CDE workload account — PCI-DSS 4.0 scope, SAQ-D level, ASV-scanned, isolated from non-CDE."
  }
  AppDev = {
    email               = "aws-appdev@example.com"
    organizational_unit = "Workloads/Dev"
    description         = "Application development account"
  }
  AppProd = {
    email               = "aws-appprod@example.com"
    organizational_unit = "Workloads/Prod"
    description         = "Application production account"
  }
}
# Workload accounts come from the frozen account inventory (02_account_hierarchy);
# empty here means none were selected.


# Existing account IDs (when known). Empty for accounts to be created.
# This map enumerates every account name the wizard knows about so
# downstream modules can `lookup(var.account_ids, "<Name>", "")`.
account_ids = {
  Management = ""
  LogArchive = ""
  Audit = ""
  SharedServices = ""
  Network = ""
  PciWorkload = ""
  AppDev = ""
  AppProd = ""
}