# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — AWS Backup tfvars (central vault + plans)
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T07:01:13.110408Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# AWS Backup central vault + backup plans
backup = {
  vault_name              = "central-vault"
  vault_kms_key_alias     = "alias/accelerator/kms/key"
  vault_lock_enabled      = true
  vault_lock_changeable_for_days = 3
  vault_lock_max_retention_days  = 2555
  vault_lock_min_retention_days  = 2555
  # Cross-region copy destination for warm-standby DR — the wrapper module
  # should create a destination vault here and a copy_action on each rule.
  secondary_region        = "us-west-2"
}

backup_plans = {
  "Daily" = {
    name = "daily-backup"
    rules = [
      {
        rule_name             = "DailyAtMidnightUTC"
        target_vault_name     = "central-vault"
        schedule              = "cron(0 5 ? * * *)"
        start_window          = 60
        completion_window     = 180
        enable_continuous_backup = false
        lifecycle = {
          cold_storage_after = 90
          delete_after       = 2555
        }
        # Replicate each daily recovery point to the DR region (warm standby).
        copy_action = {
          destination_region = "us-west-2"
          cold_storage_after = 90
          delete_after       = 2555
        }
        recovery_point_tags = {
          ManagedBy = "Merlin-Studio-v2"
        }
      }
    ]
    selection = {
      iam_role_arn  = "PLACEHOLDER_ARN_BackupRole"
      tag_key       = "Backup"
      tag_value     = "true"
      resources     = ["*"]
    }
  }
}