# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — AWS CloudTrail tfvars (organization trail + S3 destination)
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T07:01:13.110408Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

cloudtrail = {
  name                          = "acme-bank-org-trail"
  is_organization_trail         = true
  is_multi_region_trail         = true
  include_global_service_events = true
  enable_log_file_validation    = true
  enable_logging                = true

  cloud_watch_logs_group_arn    = "PLACEHOLDER_ARN_CloudTrailLogGroup"
  cloud_watch_logs_role_arn     = "PLACEHOLDER_ARN_CloudTrailRole"

  s3_bucket_name                = "PLACEHOLDER_BUCKET_NAME_CentralLogs"
  s3_key_prefix                 = "cloudtrail"

  kms_key_id                    = "alias/accelerator/kms/central-logs-key"

  # Feature flags from generators/aws_cloudtrail_features.py.
  insight_selectors = [
    { insight_type = "ApiErrorRateInsight" },
  ]

  event_selectors = [
    {
      read_write_type           = "All"
      include_management_events = true
      data_resources = [
        {
          type   = "AWS::S3::Object"
          values = ["arn:aws:s3"]
        },
      ]
    }
  ]

  advanced_event_selectors = []
}