# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — tfvars hybrid_connectivity — Direct Connect + Site-to-Site VPN + Client VPN (wizard section 05)
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T07:01:13.110408Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Consumed by the hybrid-connectivity module. External dependencies the wizard
# cannot create (physical DX circuit, on-prem device IPs, ACM/SAML material) are
# PLACEHOLDER_ tokens — see PLACEHOLDERS.md.
hybrid_connectivity = {
  account = "Network"
  region  = "us-east-2"

  direct_connect = { enabled = false }

  site_to_site_vpn = {
    enabled = true
    connections = [
      { name = "onprem-primary", customer_gateway_ip = "203.0.113.1", bgp_asn = 65000, static_routes_only = true, static_routes = ["10.100.0.0/16"], tunnel_inside_cidr = "169.254.10.0/30", transit_gateway = "main-tgw" },
    ]
  }

  client_vpn = { enabled = false }
}