# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — AWS network tfvars (consumed by terraform-aws-modules/vpc/aws ~> 5.0)
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T07:01:13.110408Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# One map entry per VPC. Module = terraform-aws-modules/vpc/aws (~> 5.0).
#
# The `account` field selects which provider alias the wrapper module
# should pass to the underlying terraform-aws-modules/vpc/aws module —
# aws.<account>[_<region>] from providers.tf (hub -> Network, spokes ->
# their workload account).

vpcs = {
  "hub" = {
    account          = "Network"
    cidr             = "10.0.0.0/16"
    azs              = ["us-east-2a", "us-east-2b"]
    private_subnets  = []
    public_subnets   = []
    intra_subnets    = ["10.0.0.0/28", "10.0.0.16/28"]
    # NAT only when the VPC has both a public subnet (to host the gateway) and
    # a private subnet to route through it; a hub VPC with only intra subnets
    # disables NAT (the module errors if it is on with no public subnet).
    enable_nat_gateway     = false
    single_nat_gateway     = false
    one_nat_gateway_per_az = false
    enable_vpn_gateway     = false
    enable_dns_hostnames   = true
    enable_dns_support     = true
    enable_flow_log        = true
    create_flow_log_cloudwatch_iam_role = true
    flow_log_max_aggregation_interval = 600
    flow_log_cloudwatch_log_group_retention_in_days = 2557
    # Gateway endpoints — same set as LZA / OpenTofu / CDK.
    gateway_endpoints = ["s3", "dynamodb"]
    # Interface endpoints (declared per-VPC) — keep ssm/secretsmanager/kms/sts/
    # logs traffic private in no-internet VPCs (e.g. the PCI CDE).
    interface_endpoints = []
    tags = {
      Name        = "hub"
      Account     = "Network"
      Region      = "us-east-2"
      Environment = "multi_env"
    }
  }
  "workloads" = {
    account          = "AppProd"
    cidr             = "10.1.0.0/16"
    azs              = ["us-east-2a", "us-east-2b"]
    private_subnets  = ["10.1.10.0/24", "10.1.11.0/24"]
    public_subnets   = []
    intra_subnets    = []
    # NAT only when the VPC has both a public subnet (to host the gateway) and
    # a private subnet to route through it; a hub VPC with only intra subnets
    # disables NAT (the module errors if it is on with no public subnet).
    enable_nat_gateway     = false
    single_nat_gateway     = false
    one_nat_gateway_per_az = false
    enable_vpn_gateway     = false
    enable_dns_hostnames   = true
    enable_dns_support     = true
    enable_flow_log        = true
    create_flow_log_cloudwatch_iam_role = true
    flow_log_max_aggregation_interval = 600
    flow_log_cloudwatch_log_group_retention_in_days = 2557
    # Gateway endpoints — same set as LZA / OpenTofu / CDK.
    gateway_endpoints = ["s3", "dynamodb"]
    # Interface endpoints (declared per-VPC) — keep ssm/secretsmanager/kms/sts/
    # logs traffic private in no-internet VPCs (e.g. the PCI CDE).
    interface_endpoints = ["ec2", "ssm", "secretsmanager", "logs"]
    tags = {
      Name        = "workloads"
      Account     = "AppProd"
      Region      = "us-east-2"
      Environment = "multi_env"
    }
  }
  "inspection" = {
    account          = "Network"
    cidr             = "10.5.0.0/16"
    azs              = ["us-east-2a", "us-east-2b"]
    private_subnets  = ["10.5.10.0/24", "10.5.11.0/24"]
    public_subnets   = ["10.5.0.0/24", "10.5.1.0/24"]
    intra_subnets    = ["10.5.20.0/24", "10.5.21.0/24"]
    # NAT only when the VPC has both a public subnet (to host the gateway) and
    # a private subnet to route through it; a hub VPC with only intra subnets
    # disables NAT (the module errors if it is on with no public subnet).
    enable_nat_gateway     = true
    single_nat_gateway     = false
    one_nat_gateway_per_az = false
    enable_vpn_gateway     = false
    enable_dns_hostnames   = true
    enable_dns_support     = true
    enable_flow_log        = true
    create_flow_log_cloudwatch_iam_role = true
    flow_log_max_aggregation_interval = 600
    flow_log_cloudwatch_log_group_retention_in_days = 2557
    # Gateway endpoints — same set as LZA / OpenTofu / CDK.
    gateway_endpoints = ["s3", "dynamodb"]
    # Interface endpoints (declared per-VPC) — keep ssm/secretsmanager/kms/sts/
    # logs traffic private in no-internet VPCs (e.g. the PCI CDE).
    interface_endpoints = []
    tags = {
      Name        = "inspection"
      Account     = "Network"
      Region      = "us-east-2"
      Environment = "multi_env"
    }
  }
  "pci-cde" = {
    account          = "PciWorkload"
    cidr             = "10.2.0.0/16"
    azs              = ["us-east-2a", "us-east-2b"]
    private_subnets  = ["10.2.10.0/24", "10.2.11.0/24"]
    public_subnets   = []
    intra_subnets    = ["10.2.20.0/24", "10.2.21.0/24"]
    # NAT only when the VPC has both a public subnet (to host the gateway) and
    # a private subnet to route through it; a hub VPC with only intra subnets
    # disables NAT (the module errors if it is on with no public subnet).
    enable_nat_gateway     = false
    single_nat_gateway     = false
    one_nat_gateway_per_az = false
    enable_vpn_gateway     = false
    enable_dns_hostnames   = true
    enable_dns_support     = true
    enable_flow_log        = true
    create_flow_log_cloudwatch_iam_role = true
    flow_log_max_aggregation_interval = 600
    flow_log_cloudwatch_log_group_retention_in_days = 2557
    # Gateway endpoints — same set as LZA / OpenTofu / CDK.
    gateway_endpoints = ["s3", "dynamodb"]
    # Interface endpoints (declared per-VPC) — keep ssm/secretsmanager/kms/sts/
    # logs traffic private in no-internet VPCs (e.g. the PCI CDE).
    interface_endpoints = ["ec2", "ssm", "secretsmanager", "kms", "logs", "sts"]
    tags = {
      Name        = "pci-cde"
      Account     = "PciWorkload"
      Region      = "us-east-2"
      Environment = "multi_env"
    }
  }
  "hub-west" = {
    account          = "Network"
    cidr             = "10.10.0.0/16"
    azs              = ["us-west-2a", "us-west-2b"]
    private_subnets  = []
    public_subnets   = []
    intra_subnets    = ["10.10.0.0/28", "10.10.0.16/28"]
    # NAT only when the VPC has both a public subnet (to host the gateway) and
    # a private subnet to route through it; a hub VPC with only intra subnets
    # disables NAT (the module errors if it is on with no public subnet).
    enable_nat_gateway     = false
    single_nat_gateway     = false
    one_nat_gateway_per_az = false
    enable_vpn_gateway     = false
    enable_dns_hostnames   = true
    enable_dns_support     = true
    enable_flow_log        = true
    create_flow_log_cloudwatch_iam_role = true
    flow_log_max_aggregation_interval = 600
    flow_log_cloudwatch_log_group_retention_in_days = 2557
    # Gateway endpoints — same set as LZA / OpenTofu / CDK.
    gateway_endpoints = ["s3", "dynamodb"]
    # Interface endpoints (declared per-VPC) — keep ssm/secretsmanager/kms/sts/
    # logs traffic private in no-internet VPCs (e.g. the PCI CDE).
    interface_endpoints = []
    tags = {
      Name        = "hub-west"
      Account     = "Network"
      Region      = "us-west-2"
      Environment = "multi_env"
    }
  }
  "workloads-west" = {
    account          = "AppProd"
    cidr             = "10.11.0.0/16"
    azs              = ["us-west-2a", "us-west-2b"]
    private_subnets  = ["10.11.10.0/24", "10.11.11.0/24"]
    public_subnets   = []
    intra_subnets    = []
    # NAT only when the VPC has both a public subnet (to host the gateway) and
    # a private subnet to route through it; a hub VPC with only intra subnets
    # disables NAT (the module errors if it is on with no public subnet).
    enable_nat_gateway     = false
    single_nat_gateway     = false
    one_nat_gateway_per_az = false
    enable_vpn_gateway     = false
    enable_dns_hostnames   = true
    enable_dns_support     = true
    enable_flow_log        = true
    create_flow_log_cloudwatch_iam_role = true
    flow_log_max_aggregation_interval = 600
    flow_log_cloudwatch_log_group_retention_in_days = 2557
    # Gateway endpoints — same set as LZA / OpenTofu / CDK.
    gateway_endpoints = ["s3", "dynamodb"]
    # Interface endpoints (declared per-VPC) — keep ssm/secretsmanager/kms/sts/
    # logs traffic private in no-internet VPCs (e.g. the PCI CDE).
    interface_endpoints = ["ec2", "ssm", "secretsmanager", "logs"]
    tags = {
      Name        = "workloads-west"
      Account     = "AppProd"
      Region      = "us-west-2"
      Environment = "multi_env"
    }
  }
}

# Transit Gateway topology (consumed by terraform-aws-modules/transit-gateway/aws
# wrappers). Multi-region: one TGW per region, a VPC attachment per VPC to the
# TGW in its region, and an inter-region peering for warm-standby DR.
transit_gateway = {
  enabled = true
  tgws = {
    "primary" = { name = "main-tgw", asn = 64512, region = "us-east-2", account = "Network", route_tables = ["tgw-associations", "tgw-propagations"] }
    "secondary" = { name = "main-tgw-west", asn = 64513, region = "us-west-2", account = "Network", route_tables = ["main-tgw-west-Associations", "main-tgw-west-Propagations"] }
  }
  attachments = {
    "hub" = { tgw = "primary", account = "Network", region = "us-east-2", route_table_association = "tgw-associations", route_table_propagations = ["tgw-associations", "tgw-propagations"] }
    "workloads" = { tgw = "primary", account = "AppProd", region = "us-east-2", route_table_association = "tgw-associations", route_table_propagations = ["tgw-associations", "tgw-propagations"] }
    "inspection" = { tgw = "primary", account = "Network", region = "us-east-2", route_table_association = "tgw-associations", route_table_propagations = ["tgw-associations", "tgw-propagations"] }
    "pci-cde" = { tgw = "primary", account = "PciWorkload", region = "us-east-2", route_table_association = "tgw-associations", route_table_propagations = ["tgw-associations", "tgw-propagations"] }
    "hub-west" = { tgw = "secondary", account = "Network", region = "us-west-2", route_table_association = "main-tgw-west-Associations", route_table_propagations = ["main-tgw-west-Associations", "main-tgw-west-Propagations"] }
    "workloads-west" = { tgw = "secondary", account = "AppProd", region = "us-west-2", route_table_association = "main-tgw-west-Associations", route_table_propagations = ["main-tgw-west-Associations", "main-tgw-west-Propagations"] }
  }
  peerings = {
    "primary-to-secondary" = { requester_tgw = "primary", requester_region = "us-east-2", accepter_tgw = "secondary", accepter_region = "us-west-2", static_routes_enabled = true }
  }
}

# Centralized egress inspection (topology SoT: generators/aws_network_topology.py).
# tfvars carries the model as data; the consuming wrapper module builds the
# hub-and-spoke + inspection VPC from it. The OpenTofu format (aws-opentofu/) is
# the reference implementation of the per-AZ data plane this describes:
#   spoke -> TGW -> inspection VPC (firewall endpoint -> NAT -> IGW), with the
#   firewall (AWS-managed strict-order stateful rule groups), TGW route domains,
#   segmented attachments, and spoke 0.0.0.0/0 -> TGW.
centralized_inspection = {
  enabled        = true
  inspection_vpc = "inspection"
  region         = "us-east-2"
  appliance_mode = true
  firewall = {
    name                     = "inspection-nfw"
    policy_name              = "inspection-nfw-policy"
    rule_order               = "STRICT_ORDER"
    stateful_rule_groups     = ["AWSManagedRulesBotNetCommandAndControlDomainsStrictOrder", "AWSManagedRulesMalwareDomainsStrictOrder", "AWSManagedRulesAbusedLegitMalwareDomainsStrictOrder"]
    stateful_default_actions = ["aws:drop_established", "aws:alert_established"]
  }
  # role -> TGW route-domain (route table) name.
  route_domains = {
    inspection = "main-tgw-inspection"
    spokes = "main-tgw-spokes"
    cde = "main-tgw-cde"
  }
  # Inspection VPC subnet tiers (isolated=TGW attach, private=firewall, public=NAT).
  inspection_vpc_plan = {
    cidr             = "10.5.0.0/16"
    azs              = ["us-east-2a", "us-east-2b"]
    tgw_subnets      = [{ "az" = "us-east-2a", "cidr" = "10.5.20.0/24", "name" = "insp-isolated-a", "az_letter" = "a" }, { "az" = "us-east-2b", "cidr" = "10.5.21.0/24", "name" = "insp-isolated-b", "az_letter" = "b" }]
    firewall_subnets = [{ "az" = "us-east-2a", "cidr" = "10.5.10.0/24", "name" = "insp-private-a", "az_letter" = "a" }, { "az" = "us-east-2b", "cidr" = "10.5.11.0/24", "name" = "insp-private-b", "az_letter" = "b" }]
    nat_subnets      = [{ "az" = "us-east-2a", "cidr" = "10.5.0.0/24", "name" = "insp-public-a", "az_letter" = "a" }, { "az" = "us-east-2b", "cidr" = "10.5.1.0/24", "name" = "insp-public-b", "az_letter" = "b" }]
    spoke_cidrs      = ["10.0.0.0/16", "10.1.0.0/16", "10.2.0.0/16", "10.10.0.0/16", "10.11.0.0/16"]
  }
  # Per-VPC route-domain association + propagation into the inspection domain.
  # `tgw` names the gateway the attachment lives on: route DOMAINS are
  # primary-only, so a DR-region attachment (tgw = the secondary) associates to
  # its own TGW's tables, NOT a primary route domain.
  attachments = {
    "hub" = { role = "workload", tgw = "main-tgw", primary = true, appliance_mode = false, route_domain = "main-tgw-spokes", propagate_to = ["main-tgw-inspection"] }
    "workloads" = { role = "workload", tgw = "main-tgw", primary = true, appliance_mode = false, route_domain = "main-tgw-spokes", propagate_to = ["main-tgw-inspection"] }
    "inspection" = { role = "inspection", tgw = "main-tgw", primary = true, appliance_mode = true, route_domain = "main-tgw-inspection", propagate_to = [] }
    "pci-cde" = { role = "cde", tgw = "main-tgw", primary = true, appliance_mode = false, route_domain = "main-tgw-cde", propagate_to = ["main-tgw-inspection"] }
    "hub-west" = { role = "workload", tgw = "main-tgw-west", primary = false, appliance_mode = false, route_domain = "main-tgw-west-Associations", propagate_to = ["main-tgw-west-Associations", "main-tgw-west-Propagations"] }
    "workloads-west" = { role = "workload", tgw = "main-tgw-west", primary = false, appliance_mode = false, route_domain = "main-tgw-west-Associations", propagate_to = ["main-tgw-west-Associations", "main-tgw-west-Propagations"] }
  }
  # Each spoke domain's 0.0.0.0/0 -> the inspection VPC attachment.
  static_routes = [
    { route_domain = "main-tgw-cde", cidr = "0.0.0.0/0", via_vpc = "inspection" },
    { route_domain = "main-tgw-spokes", cidr = "0.0.0.0/0", via_vpc = "inspection" },
  ]
  # Secondary (DR) TGW route tables — created on the secondary gateway, since
  # route domains exist only on the primary. DR-region attachments associate here.
  secondary_route_tables = [
    { tgw = "main-tgw-west", region = "us-west-2", name = "main-tgw-west-Associations" },
    { tgw = "main-tgw-west", region = "us-west-2", name = "main-tgw-west-Propagations" },
  ]
  # Inter-region peering route wiring. side=secondary: DR association table
  # 0.0.0.0/0 -> peering (egress inspected in the primary region). side=primary:
  # inspection domain routes each DR CIDR back over the peering (return path).
  peering_routes = [
    { side = "secondary", tgw = "main-tgw-west", route_table = "main-tgw-west-Associations", cidr = "0.0.0.0/0", peering = "primary-to-secondary" },
    { side = "primary", tgw = "main-tgw", route_table = "main-tgw-inspection", cidr = "10.10.0.0/16", peering = "primary-to-secondary" },
    { side = "primary", tgw = "main-tgw", route_table = "main-tgw-inspection", cidr = "10.11.0.0/16", peering = "primary-to-secondary" },
  ]
}
