# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — AWS Organizations tfvars (consumed by hashicorp/aws ~> 5.x)
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T07:01:13.110408Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# AWS Organizations + OU tree variables.
# Designed for a thin Terraform module that wraps:
#   - aws_organizations_organization
#   - aws_organizations_organizational_unit

organization_feature_set     = "ALL"
organization_aws_service_access_principals = [
  "cloudtrail.amazonaws.com",
  "config.amazonaws.com",
  "controltower.amazonaws.com",
  "guardduty.amazonaws.com",
  "securityhub.amazonaws.com",
  "ram.amazonaws.com",
  "sso.amazonaws.com",
  "tagpolicies.tag.amazonaws.com",
  "fms.amazonaws.com",
]
organization_enabled_policy_types = [
  "SERVICE_CONTROL_POLICY",
  "TAG_POLICY",
  "BACKUP_POLICY",
]

# OU tree — source of truth: generators/aws_ou_tree.py. Covers the profile
# baseline, custom OUs, and every OU an account is assigned to (incl. nested
# paths like Workloads/Prod/PHI), so the consuming module can place every
# account. The module should create parents before children.
organizational_units = {
  "Security" = { parent = "Root" }
  "Workloads" = { parent = "Root" }
  "Suspended" = { parent = "Root" }
  "Infrastructure" = { parent = "Root" }
  "Workloads/Dev" = { parent = "Workloads" }
  "Workloads/Prod" = { parent = "Workloads" }
  "Workloads/Prod/PCI" = { parent = "Workloads/Prod" }
}

# Tags applied to OUs and the org-level resources where supported.
default_tags = {
  ManagedBy    = "Merlin-Studio-v2"
  Organization = "Acme Bank"
  Profile      = "standard"
}

# Service Control Policies — set sourced from generators/aws_scp_policies.py so
# every format enforces the same guardrails (Quarantine, deny disabling
# CloudTrail/Config/GuardDuty/Security Hub, sandbox cost guardrails, region
# restrictions). The consuming module emits one aws_organizations_policy per
# entry. Empty when SCPs are disabled.
service_control_policies = {
  "Quarantine-Policy" = {
    description = "Deny all actions for newly created accounts until reviewed."
    targets     = ["Suspended"]
    policy_json = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyAllNewAccounts", "Effect" = "Deny", "Action" = "*", "Resource" = "*", "Condition" = { "ArnNotLikeIfExists" = { "aws:PrincipalArn" = ["arn:aws:iam::*:role/OrganizationAccountAccessRole", "arn:aws:iam::*:role/AWSControlTowerExecution"] } } }] })
  }
  "Guardrails-Security" = {
    description = "Deny disabling CloudTrail/Config/GuardDuty/Security Hub. Attached to Workloads + Infrastructure — every member account that must never turn off a security service. The Security OU is intentionally excluded: it holds the delegated administrator (Audit), which legitimately calls GuardDuty/Security Hub member-management APIs this policy denies. (Targeting only Security — or Root — would either leave workloads unprotected or break the delegated admin.)"
    strategy    = "deny-list"
    targets     = ["Workloads", "Infrastructure"]
    policy_json = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyDisableCloudTrail", "Effect" = "Deny", "Action" = ["cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:PutEventSelectors", "cloudtrail:UpdateTrail"], "Resource" = "*" }, { "Sid" = "DenyDisableConfig", "Effect" = "Deny", "Action" = ["config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder", "config:DeleteDeliveryChannel", "config:DeleteConfigRule", "config:DeleteOrganizationConfigRule"], "Resource" = "*" }, { "Sid" = "DenyDisableGuardDuty", "Effect" = "Deny", "Action" = ["guardduty:DeleteDetector", "guardduty:UpdateDetector", "guardduty:DisassociateFromMasterAccount", "guardduty:DisassociateMembers", "guardduty:DeleteMembers", "guardduty:StopMonitoringMembers"], "Resource" = "*" }, { "Sid" = "DenyDisableSecurityHub", "Effect" = "Deny", "Action" = ["securityhub:DisableSecurityHub", "securityhub:DisassociateFromAdministratorAccount", "securityhub:DeleteMembers", "securityhub:DisassociateMembers"], "Resource" = "*" }] })
  }
  "Protect-Security-Services" = {
    description = "Deny disabling CloudTrail / Config / GuardDuty / Security Hub at any account in the org. NIS2 Art 21 risk-management; FedRAMP/NIST SI-4 + CA-7 monitoring integrity; HIPAA admin safeguards; PCI-DSS Req 10 audit-log protection."
    strategy    = "deny-list"
    targets     = ["Root"]
    policy_json = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyDisableCloudTrail", "Effect" = "Deny", "Action" = ["cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:PutEventSelectors", "cloudtrail:UpdateTrail"], "Resource" = "*" }, { "Sid" = "DenyDisableConfig", "Effect" = "Deny", "Action" = ["config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder", "config:DeleteDeliveryChannel", "config:DeleteConfigRule", "config:DeleteOrganizationConfigRule"], "Resource" = "*" }, { "Sid" = "DenyDisableGuardDuty", "Effect" = "Deny", "Action" = ["guardduty:DeleteDetector", "guardduty:UpdateDetector", "guardduty:DisassociateFromMasterAccount", "guardduty:DisassociateMembers", "guardduty:DeleteMembers", "guardduty:StopMonitoringMembers"], "Resource" = "*" }, { "Sid" = "DenyDisableSecurityHub", "Effect" = "Deny", "Action" = ["securityhub:DisableSecurityHub", "securityhub:DisassociateFromAdministratorAccount", "securityhub:DeleteMembers", "securityhub:DisassociateMembers"], "Resource" = "*" }] })
  }
  "Require-IMDSv2" = {
    description = "Deny launching EC2 instances without IMDSv2 (http_tokens=required) and deny weakening the metadata options afterwards. Prevention paired with the ec2-imdsv2-check Config rule's detection. CIS 5.4/5.6; NIST/FedRAMP AC-3 + SC-23; PCI-DSS Req 2; HIPAA technical safeguards."
    strategy    = "deny-list"
    targets     = ["Root"]
    policy_json = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyRunInstancesWithoutImdsv2", "Effect" = "Deny", "Action" = "ec2:RunInstances", "Resource" = "arn:aws:ec2:*:*:instance/*", "Condition" = { "StringNotEquals" = { "ec2:MetadataHttpTokens" = "required" } } }, { "Sid" = "DenyDowngradingMetadataOptions", "Effect" = "Deny", "Action" = "ec2:ModifyInstanceMetadataOptions", "Resource" = "*", "Condition" = { "StringNotEquals" = { "ec2:MetadataHttpTokens" = "required" } } }] })
  }
  "Deny-Root-Access" = {
    description = "Deny all actions by the account root user (CIS 1.7 / Control Tower 'disallow root' guardrail). Break-glass is preserved: the condition only matches the root principal, so IAM roles/users are unaffected (use a break-glass admin role), and SCPs never apply to the organization management account's root."
    strategy    = "deny-list"
    targets     = ["Workloads"]
    policy_json = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyRootUserActions", "Effect" = "Deny", "Action" = "*", "Resource" = "*", "Condition" = { "StringLike" = { "aws:PrincipalArn" = "arn:aws:iam::*:root" } } }] })
  }
}

# Policy → OU attachment map. The consuming module emits one
# aws_organizations_policy_attachment per (policy, OU).
scp_attachments = {
  "Quarantine-Policy" = ["Suspended"]
  "Guardrails-Security" = ["Workloads", "Infrastructure"]
  "Protect-Security-Services" = ["Root"]
  "Require-IMDSv2" = ["Root"]
  "Deny-Root-Access" = ["Workloads"]
}