# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — AWS security tfvars (GuardDuty, Security Hub, Config, Macie, Access Analyzer)
# Organization: Acme Bank
# Profile:      STANDARD
# Generated:    2026-06-14T07:01:13.110408Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.
# Compliance frameworks declared on this spec:
#   - cis
#   - pci_dss
#   - sox

home_region      = "us-east-2"
enabled_regions  = ["us-east-1", "us-east-2", "us-west-1", "us-west-2"]
audit_account_id = "PLACEHOLDER_ACCOUNT_ID_Audit"

guardduty = {
  enabled                     = true
  auto_enable_org_members     = true
  finding_publishing_frequency = "FIFTEEN_MINUTES"
  s3_protection_enabled       = true
  eks_protection_enabled      = true
  malware_protection_enabled  = true
  rds_protection_enabled      = true
  lambda_protection_enabled   = true
  finding_retention_days      = 365
}

security_hub = {
  enabled              = true
  region_aggregation   = true
  auto_enable_controls = true
  standards = ["aws-foundational-security-best-practices/v/1.0.0", "cis-aws-foundations-benchmark/v/1.4.0", "pci-dss/v/3.2.1"]
}

aws_config = {
  enabled            = true
  aggregator_enabled = true
  aggregator_regions = ["us-east-1", "us-east-2", "us-west-1", "us-west-2"]
  recorder_role_arn  = ""
  delivery_channel_s3_bucket = ""   # filled in from S3 log archive output
}

macie = {
  enabled = true
  finding_publishing_frequency = "FIFTEEN_MINUTES"
  finding_retention_days       = 365
}

access_analyzer = {
  enabled = true
  type    = "ORGANIZATION"
}

inspector = {
  enabled = true
  resource_types = ["EC2", "ECR", "LAMBDA"]
}

detective = {
  enabled = false
}

iam_password_policy = {
  minimum_password_length        = 14
  require_lowercase_characters   = true
  require_uppercase_characters   = true
  require_numbers                = true
  require_symbols                = true
  allow_users_to_change_password = true
  hard_expiry                    = false
  max_password_age               = 90
  password_reuse_prevention      = 24
}

s3_account_public_access_block = {
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

ebs_default_encryption = {
  enabled    = true
  # encryption_requirements=cmk -> default EBS to the workload CMK, not aws/ebs.
  kms_key_id = "alias/workload/default"
}

# Budgets ($1000/mo for simple; alerts at 80% and 100%). The module that
# consumes this should iterate over budgets[] to create one aws_budgets_budget
# per workload account.
budgets = {
  enabled                   = true
  default_monthly_budget    = 10000
  alert_thresholds          = [80, 100]
  anomaly_detection_enabled = true
  anomaly_threshold_amount  = 100
}